ARG VERSION_KSQLDB

FROM confluentinc/ksqldb-server:${VERSION_KSQLDB}

ARG VERSION_CONFLUENT
# https://docs.confluent.io/current/control-center/installation/clients.html
RUN mkdir -p /usr/share/java/monitoring-interceptors \
    && curl -L http://packages.confluent.io/maven/io/confluent/monitoring-interceptors/${VERSION_CONFLUENT}/monitoring-interceptors-${VERSION_CONFLUENT}.jar \
        -o /usr/share/java/monitoring-interceptors/monitoring-interceptors-${VERSION_CONFLUENT}.jar
ENV KSQL_CLASSPATH=/usr/share/java/my-base/*:/usr/share/java/my-ksql-server/*:/usr/share/java/monitoring-interceptors/*

ARG OPENTRACING_SPECIALAGENT_VERSION=1.7.4
RUN mkdir -p /usr/share/java/tracing-agents \
    && curl -L https://repo1.maven.org/maven2/io/opentracing/contrib/specialagent/opentracing-specialagent/${OPENTRACING_SPECIALAGENT_VERSION}/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar \
        -o /usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar
ENV KSQL_OPTS="-javaagent:/usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar"
ARG OPENTRACING_SPECIALAGENT_EXPORTER=jaeger
ENV KSQL_OPTS="${KSQL_OPTS} -Dsa.exporter=${OPENTRACING_SPECIALAGENT_EXPORTER}"
ENV KSQL_CLASSPATH="${KSQL_CLASSPATH}:/usr/share/java/tracing-agents/*"

#ARG OPENTRACING_KAFKA_CLIENT_VERSION=0.1.13
#RUN mkdir -p /usr/share/java/tracing-interceptors \
#    && curl -L https://repo1.maven.org/maven2/io/opentracing/contrib/opentracing-kafka-client/${OPENTRACING_KAFKA_CLIENT_VERSION}/opentracing-kafka-client-${OPENTRACING_KAFKA_CLIENT_VERSION}.jar \
#        -o /usr/share/java/tracing-interceptors/opentracing-kafka-client-${OPENTRACING_KAFKA_CLIENT_VERSION}.jar
#ENV KSQL_CLASSPATH="${KSQL_CLASSPATH}:/usr/share/java/tracing-interceptors/*"