Showcase Emob
-------------

Requirements
~~~~~~~~~~~~

The following Kafka connectors are required:

- MQTT connector: https://www.confluent.io/hub/confluentinc/kafka-connect-mqtt 
- MongoDB connector: https://www.confluent.io/hub/mongodb/kafka-connect-mongodb

clone the git-repository
----
cd ./showcase
docker-compose down
rm docker-compose.yml
cd ..
git clone https://github.com/NovatecConsulting/technologyconsulting-showcase-emob.git
----

Create the showcase network
----
docker network create showcase_emob
----


Quickstart
~~~~~~~~~~
.Change in the showcase directory, create the following subfolder _/connectors/jars_ and extract the downloaded connectors to it.
----
cd ./technologyconsulting-showcase-emob
----

.Start the showcase from the base directory of the showcase (technologyconsulting-showcase-emob)
----
docker-compose up
----

.Wait until all components and modules (especially) _connect_ are up. Verify with 
----
docker-compose ps
----

.Configure the MQTT and MongoDB connectors. Verify that the following shell-scripts are executable by chmod 777

----
chmod 777 connectors-config.sh
./connectors-config.sh
----
./connec  
.Test the end-to-end connection of two connectors (chmod 777 if necessary)
----
chmod 777 test-connect.sh
./test-connect.sh
----

 * The end-to-end test publishes some sample messages to topic _test_ on HiveMQ broker. 
 * These messages are imported to Kafka topic _connect-topic_ with _mqtt-source_ connector. This topic can be inspected from control center.
 * The records in _connect-topic_ are exported to MongoDB with _mongodb-sink_ connector. The MongoDB can be inspected with MongoDB client on _localhost:3000_. On MongoDB client, connect to MongoDB using the _Default (preconfigured)_ connection.

.Stop the showcase 
----
docker-compose down
----



Network and Credentials
~~~~~~~~~~~~~~~~~~~~~~~

[options="header"]
.Credentials
|===
| Service | Username | Password
| hivemq  | admin    | hivemq
|===


[cols="h,1"]
.Access to services from host
|===
| Kafka Bootstrap Server|  localhost:9092
| Schema Registry Url | localhost:8081
| Confluent Control Center | localhost:9021 
| Kafka Connect | localhost:8083
| HiveMQ Broker | localhost:8080
| MongoDB client| localhost:3000
|===

![Alt text](https://g.gravizo.com/source/custom_mark10?https%3A%2F%2Fraw.githubusercontent.com%2FTLmaK0%2Fgravizo%2Fmaster%2FREADME.md)
<details> 
<summary></summary>
custom_mark10
  digraph G {
    size ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf};
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
custom_mark10
</details>


