ARG VERSION_KSQLDB

FROM openjdk:11-jdk-slim as builder-functions
WORKDIR /workspace
# first load all dependencies, in order to avoid download for every build
COPY lib/ksql-functions/pom.xml lib/ksql-functions/mvnw ./
COPY lib/ksql-functions/.mvn ./.mvn
RUN ./mvnw dependency:go-offline
# second build jar
COPY lib/ksql-functions .
RUN ./mvnw clean install

FROM openjdk:11-jdk-slim as builder-interceptors
WORKDIR /workspace
# first load all dependencies, in order to avoid download for every build
COPY lib/novatec-kafka-streams-interceptors/pom.xml lib/novatec-kafka-streams-interceptors/mvnw ./
COPY lib/novatec-kafka-streams-interceptors/.mvn ./.mvn
RUN ./mvnw dependency:go-offline
# second build jar
COPY lib/novatec-kafka-streams-interceptors .
RUN ./mvnw clean install

FROM confluentinc/ksqldb-server:${VERSION_KSQLDB}

ARG VERSION_CONFLUENT
# https://docs.confluent.io/current/control-center/installation/clients.html
RUN mkdir -p /usr/share/java/monitoring-interceptors \
    && curl -L http://packages.confluent.io/maven/io/confluent/monitoring-interceptors/${VERSION_CONFLUENT}/monitoring-interceptors-${VERSION_CONFLUENT}.jar \
        -o /usr/share/java/monitoring-interceptors/monitoring-interceptors-${VERSION_CONFLUENT}.jar
ENV KSQL_CLASSPATH=/usr/share/java/my-base/*:/usr/share/java/my-ksql-server/*:/usr/share/java/monitoring-interceptors/*

ARG OPENTRACING_SPECIALAGENT_VERSION=1.7.4
RUN mkdir -p /usr/share/java/tracing-agents \
    && curl -L https://repo1.maven.org/maven2/io/opentracing/contrib/specialagent/opentracing-specialagent/${OPENTRACING_SPECIALAGENT_VERSION}/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar \
        -o /usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar
ENV KSQL_OPTS="${KSQL_OPTS} -javaagent:/usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar"
ARG OPENTRACING_SPECIALAGENT_EXPORTER=mock
ENV OPENTRACING_SPECIALAGENT_EXPORTER=${OPENTRACING_SPECIALAGENT_EXPORTER}
RUN printf "# Opentracing agent\n[[ -n \"\${OPENTRACING_SPECIALAGENT_EXPORTER}\" ]] && export KSQL_OPTS=\"\${KSQL_OPTS} -Dsa.exporter=\${OPENTRACING_SPECIALAGENT_EXPORTER}\"\n" >> /usr/bin/docker/ksqldb-env \
    && sed -i '/^#\!\/usr\/bin\/env bash.*/a. \/usr\/bin\/docker\/ksqldb-env' /usr/bin/docker/run
ENV KSQL_CLASSPATH="${KSQL_CLASSPATH}:/usr/share/java/tracing-agents/*"

COPY --from=builder-functions /workspace/target/*.jar /etc/ksql/ext/

COPY --from=builder-interceptors /workspace/target/*.jar /usr/share/java/custom-interceptors/
ENV KSQL_CLASSPATH="${KSQL_CLASSPATH}:/usr/share/java/custom-interceptors/*"