ARG VERSION_CONFLUENT

FROM openjdk:11-jdk-slim as builder
WORKDIR /workspace
COPY lib/novatec-kafka-connect-transforms .
RUN ./gradlew clean build

FROM confluentinc/cp-server-connect-base:${VERSION_CONFLUENT}
# CLASSPATH required due to CC-2422
ENV CLASSPATH="${CLASSPATH}:/usr/share/java/monitoring-interceptors/*"

ARG CONNECTORS=""
RUN for c in ${CONNECTORS}; do confluent-hub install --no-prompt $c; done;

ARG OPENTRACING_SPECIALAGENT_VERSION=1.7.4
RUN mkdir -p /usr/share/java/tracing-agents \
    && curl -L https://repo1.maven.org/maven2/io/opentracing/contrib/specialagent/opentracing-specialagent/${OPENTRACING_SPECIALAGENT_VERSION}/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar \
        -o /usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar
ENV KAFKA_OPTS="${KAFKA_OPTS} -javaagent:/usr/share/java/tracing-agents/opentracing-specialagent-${OPENTRACING_SPECIALAGENT_VERSION}.jar"
ARG OPENTRACING_SPECIALAGENT_EXPORTER=mock
ENV OPENTRACING_SPECIALAGENT_EXPORTER=${OPENTRACING_SPECIALAGENT_EXPORTER}
RUN printf "\n# Opentracing agent\n[[ -n \"\${OPENTRACING_SPECIALAGENT_EXPORTER}\" ]] && export KAFKA_OPTS=\"\${KAFKA_OPTS} -Dsa.exporter=\${OPENTRACING_SPECIALAGENT_EXPORTER}\"\n" >> /etc/confluent/docker/bash-config
ENV CLASSPATH="${CLASSPATH}:/usr/share/java/tracing-agents/*"

COPY --from=builder /workspace/build/libs /usr/share/java/custom-transforms
ENV CLASSPATH="${CLASSPATH}:/usr/share/java/custom-transforms/*"
